menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/fengxianhe
    GitHub: https://github.com/hefengxian
    Coding: https://coding.net/u/hfx
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo: hefengxian

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2016

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
